=== KMenden/CSCI3916-HW1/movies.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified"
           targetNamespace="http://sample"
           xmlns="http://sample"
           elementFormDefault="qualified"
           xmlns:xs="http://www.w3.org/2001/XMLSchema">
        <xs:element name="movies">
            <xs:complexType>
                <xs:sequence>
                    <xs:element name="movie" maxOccurs="unbounded">
                        <xs:complexType>
                            <xs:sequence>
                                <xs:element name="Title">
                                    <xs:simpleType>
                                        <xs:restriction base="xs:string">
                                            <xs:minLength value="1"/>
                                        </xs:restriction>
                                    </xs:simpleType>
                                </xs:element>
                                <xs:element name="Year">
                                    <xs:simpleType>
                                        <xs:restriction base="xs:integer">
                                            <xs:totalDigits value="4"/>
                                        </xs:restriction>
                                    </xs:simpleType>
                                </xs:element>
                                <xs:element name="Genre">
                                    <xs:simpleType>
                                        <xs:restriction base="xs:string">
                                            <xs:enumeration value="Action"/>
                                            <xs:enumeration value="Adventure"/>
                                            <xs:enumeration value="Comedy"/>
                                            <xs:enumeration value="Drama"/>
                                            <xs:enumeration value="Fantasy"/>
                                            <xs:enumeration value="Horror"/>
                                            <xs:enumeration value="Mystery"/>
                                            <xs:enumeration value="Thriller"/>
                                            <xs:enumeration value="Western"/>
                                        </xs:restriction>
                                    </xs:simpleType>
                                </xs:element>
                                <xs:element name="Actors">
                                    <xs:complexType>
                                        <xs:sequence>
                                            <xs:element name="Actor" maxOccurs="unbounded">
                                                <xs:complexType>
                                                    <xs:sequence>
                                                        <xs:element name="Name">
                                                            <xs:simpleType>
                                                                <xs:restriction base="xs:string">
                                                                    <xs:minLength value="1"/>
                                                                </xs:restriction>
                                                            </xs:simpleType>
                                                        </xs:element>
                                                        <xs:element name="DateofBirth">
                                                            <xs:simpleType>
                                                                <xs:restriction base="xs:date">
                                                                    <xs:pattern value="[1-2]\d\d\d-[0-1][0-9]-[0-3][0-9]"/>
                                                                </xs:restriction>
                                                            </xs:simpleType>
                                                        </xs:element>
                                                    </xs:sequence>
                                                </xs:complexType>
                                            </xs:element>
                                        </xs:sequence>
                                    </xs:complexType>
                                </xs:element>
                            </xs:sequence>
                        </xs:complexType>
                    </xs:element>
                </xs:sequence>
            </xs:complexType>
        </xs:element>
</xs:schema>

=== KMenden/CSCI3916-HW1/movies.xml
<?xml version="1.0"?>
<movies
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns="http://sample"
        xsi:schemaLocation="http://sample movies.xsd">
    <movie>
        <Title>12 Angry Men</Title>
        <Year>1957</Year>
        <Genre>Drama</Genre>
        <Actors>
           <Actor>
               <Name>Henry Fonda</Name>
               <DateofBirth>1905-05-16</DateofBirth>
           </Actor>
            <Actor>
                <Name>Lee J. Cobb</Name>
                <DateofBirth>1911-12-08</DateofBirth>
            </Actor>
            <Actor>
                <Name>Ed Begley Sr.</Name>
                <DateofBirth>1901-03-25</DateofBirth>
            </Actor>
            <Actor>
                <Name>E.G. Marshall</Name>
                <DateofBirth>1914-06-18</DateofBirth>
            </Actor>
            <Actor>
                <Name>Jack Warden</Name>
                <DateofBirth>1920-09-18</DateofBirth>
            </Actor>
        </Actors>
    </movie>
    <movie>
        <Title>S.W.A.T</Title>
        <Year>2003</Year>
        <Genre>Action</Genre>
        <Actors>
            <Actor>
                <Name>Samual L. Jackson</Name>
                <DateofBirth>1948-12-21</DateofBirth>
            </Actor>
            <Actor>
                <Name>Colin Farrell</Name>
                <DateofBirth>1976-05-31</DateofBirth>
            </Actor>
            <Actor>
                <Name>Michelle Rodriguez</Name>
                <DateofBirth>1978-07-12</DateofBirth>
            </Actor>
            <Actor>
                <Name>LL Cool J</Name>
                <DateofBirth>1968-01-14</DateofBirth>
            </Actor>
        </Actors>
    </movie>
</movies>
